### PR TITLE
added ability to choose color by name

### PR DESCRIPTION
**Pull request by Back-Slash-N**
added a bunch of preset colors for players to choose by name.

### CODE REVIEW

**Comment by OrsellGaming** [comment]
There are a few problems with this so no merging yet, I'll address them in DMs when I get home. On a positive note however, this is actually better than previous works you've done, so good job.

**Comment by cabiste69** [comment]
address the issues here.

**Comment by OrsellGaming** [comment]
There are better ways to handle the arguments, plus there is already a function that has a list of all our colors so we can adjust it to work with the `!playercolor` chat command. Also, some ways variables are handled works but are tacky, this relates to the arguments bit.

**Comment by cabiste69** [comment]
>args issue

that's the best way to handle them under this system considering the function should now accept either 1 or 3 args

>function duplication

that one is true but we wanted something that would work quickly, we'll be rewriting soon™️ to use the existing function

>janky solutions

yeah unfortunately the entire code base is jank so you can't really expect eloquent solutions, even tho we tried our best to make it as clean as possible

**Pull request merged**
