### PR TITLE
I've added comments stuff

### PR DESCRIPTION
**Pull request by MeblIkea**

### CODE REVIEW

**Comment by cabiste69** [comment]
would you mind describing what this adds and please remember that this repo will be abandoned in the next few weeks, also move this from [dev](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/tree/dev) to [finalcleanup](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/tree/finalcleanup)

**Comment by MeblIkea** [comment]
Hello, I came back from work, got on my computer, went on GitHub, forked the project, and added a comment. Now I'm on my Pixel 2 XL, and I don't know if I can do that on my Pixel 2 XL.
https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/assets/69876322/0be39a99-3d15-434d-b213-92a0e1a6f191

**Comment by OrsellGaming** [comment]
@MeblIkea is to-new.py suppose to be a JSON formater for the language translation files? I've looked up what the ast module is but I’m still not sure what exactly it does.

**Comment by cabiste69** [comment]
closing this for the lack of description and explanation

**Pull request closed without merging**
