### PR TITLE
new Korean

### PR DESCRIPTION
**Pull request by maldron0309**
I've also worked on additional translations
I'm a little confused about whether I should push to the development branch or the main branch.....

### CODE REVIEW

**Comment by OrsellGaming** [comment]
@maldron0309 You've got it correct. The `dev` branch should merge into the `dev` branch.

One thing you appear to have forgotten with this PR was the README you initially translated. Overall this all looks correct, I just need to test this out myself to see if everything looks correct. After you upload the README I'll be able to check that too then once I confirm all is in order I can merge and close this PR.

**Comment by maldron0309** [comment]
I forgot to commit the README, thanks for the nice feedback :)

**Comment by OrsellGaming** [comment]
Hi @maldron0309 are you able to upload the README?

**Review by OrsellGaming — APPROVED** [review]

**Comment by OrsellGaming** [comment]
Hi @maldron0309, everything looks good! I'll be going ahead and merging this into `dev`. Thank you for your contribution!

**Comment by maldron0309** [comment]
Thanks for the merge, I'll be happy to contribute in the future :)

**Comment by OrsellGaming** [comment]
Hi @maldron0309 , just a heads up that some new translations will be coming to the launcher at some point, so I will need to request some help on those once they are committed to `dev`. Is that alright?

**Comment by maldron0309** [comment]
Sure! Just let me know when they're committed to dev, and I'll be happy to help

**Pull request merged**
