### PR TITLE
Fixed config button having no attribute 'x' error

### PR DESCRIPTION
**Pull request by Back-Slash-N**
fuck u orsell <3

### CODE REVIEW

**Comment by cabiste69** [comment]
It may look like a joke pr, but this is an actual fix

**Comment by OrsellGaming** [comment]
I tried that before, it doesn't fix it

**Comment by cabiste69** [comment]
> I tried that before, it doesn't fix it

it actually does, don't even ask me why or how, it just

**Comment by OrsellGaming** [comment]
That makes no sense, but ok I guess

**Review by OrsellGaming — CHANGES_REQUESTED** [review]
Remove the dumb stuff then you're fine

**Pull request merged**
